# =======================
#   Development Image
# =======================
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /src

# Copy csproj trước để restore cache
COPY *.csproj .
RUN dotnet restore

# Copy toàn bộ source
COPY . .

# Sử dụng ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_ENVIRONMENT=Development

# Swagger sẽ tự bật ở môi trường Development (nếu bạn cấu hình đúng)
# dotnet watch để reload code real time
CMD ["dotnet", "run", "--urls", "http://0.0.0.0:8080"]
